FROM golang:alpine

# Install protoc
RUN apk add --update-cache \
  git \
  nodejs-current-npm \
  protobuf \
  protobuf-dev \
  cmake \
  g++ \
  make


# Install protoc plugins
RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get -u github.com/twitchtv/twirp/protoc-gen-twirp
RUN npm install -g long ts-proto@^1.37.0
