name: PR CI

# For all PRs to the master branch compile the code and run static analysis
on:
  pull_request:
    branches: master

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"

      - name: Cache pre-commit's installed hooks
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit static analyzers
        uses: pre-commit/action@v1.0.1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["base", "webservices"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Use the Github Actions cache to cache our container image layers.
      # The tradeoffs relative to using the container registry as a cache are not yet clear.
      # For example:
      # - Using Dockerhub as a cache would allow local builds and CI builds to share the same cache.
      # - Dockerhub has announced a rate-limit of 200 pulls/6 hrs for unpaid accounts.
      # - The Github cache evicts when it grows above 5GB.
      # - The Github cache has nice built-in support for "fallback" cache keys
      # To use Dockerhub as a cache instead, replace the cache-from/cache-to lines below with:
      #   cache-from: type=registry,ref=farmng/${{ matrix.image }}:latest
      #   cache-to: type=inline,mode=max
      # (taking care to choose appropriate cache keys)
      # see https://github.com/docker/buildx#--cache-fromnametypetypekeyvalue)
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image }}-
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/${{ matrix.image }}.Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
