name: Publish Language-Specific Packages

# For all releases (tags beginning with 'v'), publish packages for all modules.
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["core"] #"calibration", "frontend", "perception", "tractor"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Build project
        run: |
          python -m pip install setuptools wheel
          cp cmake/setup.py.template modules/${{ matrix.module }}/python/setup.py
          cp LICENSE modules/${{ matrix.module }}/python
          cd modules/${{ matrix.module }}/python
          touch farm_ng/__init__.py
          touch farm_ng/${{ matrix.module }}/__init__.py
          python setup.py sdist bdist_wheel

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          packages_dir: modules/${{ matrix.module }}/python/dist
          repository_url: https://test.pypi.org/legacy/
