name: Publish Source to GH Releases

# For all releases (tags beginning with 'v'), publish source archives for all modules.
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        module: ["core", "frontend_core", "perception_core", "tractor"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build project
        run: |
          tar -czvf ${{ matrix.module }}.tar.gz modules/${{ matrix.module }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.module }}.tar.gz
          asset_name: ${{ matrix.module }}.tar.gz
          asset_content_type: application/gzip
